# Pytorch Fundamentals

## Importing Pytorch

In [1]:
%pip install numpy
%pip install pandas
%pip install matplotlib

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cpu


## Introduction to Tensors

### Creating tensors

#### Scalar

Scalars can be created using `torch.tensor()`

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

You can use `ndim` to find the dimensions of a tensor. A scalar is a 0-dimensional tensor

In [4]:
scalar.ndim

0

The `item()` method can be used to convert a scalar to an integer type

In [5]:
scalar.item()

7

#### Vector

In [6]:
vector = torch.tensor([7, 7])
print(vector)

tensor([7, 7])


Vectors are one-dimensional

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

This indicates that the vector has 2 elements in it.

#### Matrix

In [9]:
MATRIX = torch.tensor([[1, 2],
                       [3, 4]])
print(MATRIX)

tensor([[1, 2],
        [3, 4]])


Matrices are 2 dimensional

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

This indicates that the matrix has 2 elements in its first dimension and 2 elements in its second dimension.

You can access elements of a tensor similar to that of python or numpy arrays.

In [12]:
MATRIX[0]

tensor([1, 2])

In [13]:
MATRIX[0][0]

tensor(1)

#### Tensor

In [14]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[1, 9, 2],
                        [4, 7, 8],
                        [9, 1, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 9, 2],
         [4, 7, 8],
         [9, 1, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([2, 3, 3])

In [17]:
TENSOR[1]

tensor([[1, 9, 2],
        [4, 7, 8],
        [9, 1, 5]])

In [18]:
TENSOR[1][0]

tensor([1, 9, 2])

### Creating random tensors

Random tensors are required because neural networks start with tensors full of random numbers and then adjust them according to the data.

We use `torch.rand()` to create a random tensor

In [19]:
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.8515, 0.8600, 0.5118, 0.8148],
         [0.7326, 0.4049, 0.1836, 0.5707],
         [0.1134, 0.2434, 0.1103, 0.5219]],

        [[0.5787, 0.7262, 0.7955, 0.9158],
         [0.8222, 0.0630, 0.1806, 0.6940],
         [0.8978, 0.3779, 0.6069, 0.2986]]])

In [20]:
random_tensor.ndim

3

In [21]:
#  Creating a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)